# Usa uma imagem Node.js estável
FROM node:24-alpine

# Define modo produção
ENV NODE_ENV=production

# Define diretório de trabalho
WORKDIR /usr/src/app

# Copia somente arquivos de dependência
COPY package.json package-lock.json ./

# Instala apenas dependências de produção
RUN npm ci --omit=dev

# Copia o restante do projeto
COPY . .

# Expõe a porta usada pela API
EXPOSE 4000

# Realiza o build e inicia o servidor
CMD ["sh", "-c", "npm run build && node dist/server.js"]
